// src/utils/MoviesStored.js
const movies = [
   {
    id: 1,
    title: "Coolie",
    image: "/images/Coolie_2_Poster-33dfdd70-71f9-11f0-8de0-9d1c38983d05.avif",
    rating: "A | 2hrs 50min",
    languages: ["Tamil","Telugu"],
    cities: ["Chennai","Goa" ,],
  },
  {
    id: 2,
    title: "The Fantastic Four: First Steps",
    image: "/poster/TheFantestic4/Fantastic-44-bfacae00-6605-11f0-b49e-0daac2dae3b7.avif",
    rating: "U/A13+ | 1hr 55min",
    languages: ["English"],
    cities: ["Chennai","Goa","Hyderabad"],
  },
  {
    id: 3,
    title: "Mahavatar Narsimha",
    image: "/poster/Mahavatar-Narsimha/Mahavatar-Narsimha--Poster-742abd40-d7c2-11ef-83bf-1dede4761f84.avif",
    rating: "UA13+ | 2hrs 11min",
    languages: ["Tamil", "and 2 more"],
    cities: ["chennai"],
  },
  {
    id: 4,
    title: "F1 The Movie",
    image: "/images/f1.avif",
    rating: "UA16",
    languages: ["English","Tamil"],
    cities: ["Chennai"],
  },
  {
    id: 5,
    title: "War2",
    image: "/poster/War/WAR2_Poster-e318ca10-6225-11f0-a47d-892349f87030.avif",
    rating: "UA16+ | 2hrs 52min",
    languages: ["Tamil","Telugu","Hindi"],
    cities: ["chennai"],
  },
  {
    id: 6,
    title: "Lokah Chapter1 : Chandra",
    image: "/images/Lokah2-9e449270-83c7-11f0-8765-35f6bb2b061d.jpg",
    rating: "UA16+ | 2hrs 31min",
    languages: ["Tamil"],
    cities: ["Chennai", "Mumbai"],
  },
  {
    id: 7,
    title: "From The World Of Jhon Wick:Ballerina",
    image: "/images/jonwick.avif",
    rating: "A",
    languages: ["Telugu", "and 1 more"],
    cities: ["Hyderabad","Goa"],
  },
  {
    id: 8,
    title: "jurassic World Rebirth",
    image: "/images/Jurrasic2.avif",
    rating: "A" | "2hrs 14min",
    languages: ["English", "Tamil","Telugu" ,"Hindi"],
    cities: ["Mumbai"],
  },
  {
    id: 9,
    title: "Kubera",
    image: "/images/Kubera.avif",
    rating: "UA13+",
    languages: ["Telugu"],
    cities: ["Chennai"],
  },
  {
    id: 10,
    title: "M.S.-Dhoni:The Untold Story(2016)",
    image: "/images/M.S.-Dhoni.avif",
    rating: "U",
    languages: ["Tamil","Hindi"],
    cities: ["Mumbai"],
  },
  {
    id: 11,
    title: "MAA",
    image: "/images/MAA.avif",
    rating: "UA16+",
    languages: ["Hindi"],
    cities: ["Chennai", "Mumbai"], 
  },
  {
    id: 12,
    title: "metro-in-dino",
    image: "/images/metro-in-dino.avif",
    rating: "UA16+",
    languages: ["Hindi" ],
    cities: ["Chennai","Goa"],
  },
  {
    id: 13,
    title: "Parandhu po",
    image: "/images/Parandhu-po.avif",
    rating: "UA13+",
    languages: ["Tamil"],
    cities: ["Mumbai"],
  },

  {
    id: 14,
    title: "Phoenix",
    image: "/images/Phoenix_Poster.avif",
    rating: "A",
    languages: ["Tamil"],
    cities: ["Chennai"],
  },
  {
    id: 15,
    title: "Maargan",
    image: "/images/poster Maargan.avif",
    rating: "UA13+",
    languages: ["English"],
    cities: ["Mumbai"],
  },
  {
    id: 16,
    title: "sitare zameen",
    image: "/images/poster sitare-zameen.avif",
    rating: "UA13+",
    languages: ["Hindi"],
    cities: ["Chennai", "Mumbai"],
  },
  {
    id: 17,
    title: "Kannapa",
    image: "/images/poster_0013_Kannapa4.avif",
    rating: "UA13+",
    languages: ["Telugu", "Tamil"],
    cities: ["Goa"],
  },
  {
    id: 18,
    title: "Mahavatar Narsimha",
    image: "/images/poster.avif",
    rating: "UA13+",
    languages: ["Tamil", "and 2 more"],
    cities: ["Mumbai"],
  },
  {
    id: 19,
    title: "Thammudu",
    image: "/images/Thammudu.avif",
    rating: "A",
    languages: ["Telugu"],
    cities: ["Chennai"],
  },
  {
    id: 20,
    title: "The Fantastic Four: First Steps",
    image: "/images/Untitle.avif",
    rating: "UA13+",
    languages: ["English"],
    cities: ["Mumbai"],
  },
  
];

export default movies;
